title: PM_TEN
description: PM_TEN web site
domain: pm10-ambiente.it
url: https://www.pm10-ambiente.it
baseurl: /
repository: https://github.com/pm-ten/pm-ten.github.io

date_format: "ordinal"

# Use the following plug-ins
plugins:
  - jemoji # Github flavored emoji
  
# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - NOTES.md
  - vendor
  - scripts
  - temp
  - docs
  - .gitignore
  - .jekyll-cache/

# Process these folders
include: [ "_pages" ]

# Apply defaults based on path
defaults:
-
  scope:
    path: '_pages/root'
  values:
    permalink: ':basename'
    type: 'root'
    sitemap: 'true'
-
  scope:
    path: '_pages/root/en'
  values:
    language: 'en'
    permalink: 'en/:basename'
    type: 'root'
    sitemap: 'true'
-
  scope:
    path: '_pages/root/it'
  values:
    language: 'it'
    permalink: 'it/:basename'
    type: 'root'
    sitemap: 'true'
-
  scope:
    path: '_pages/home/en'
  values:
    language: 'en'
    permalink: ':basename'
    layout: 'home'
    type: 'root'
    sitemap: 'true'
-
  scope:
    path: '_pages/home/it'
  values:
    language: 'it'
    permalink: ':basename'
    layout: 'home'
    type: 'root'
    sitemap: 'true'
-
  scope:
    path: '_pages/services/en'
  values:
    layout: service
    language: 'en'
    permalink: 'en/services/:basename'
    type: 'service'
    sitemap: 'true'
-
  scope:
    path: '_pages/services/it'
  values:
    layout: service
    language: 'it'
    permalink: 'it/servizi/:basename'
    type: 'service'
    sitemap: 'true'
-
  scope:
    path: '_pages/people/en'
  values:
    layout: person
    language: 'en'
    permalink: 'en/people/:basename'
    type: 'person'
    sitemap: 'true'
-
  scope:
    path: '_pages/people/it'
  values:
    layout: person
    language: 'it'
    permalink: 'it/persone/:basename'
    type: 'person'
    sitemap: 'true'
-
  scope:
    path: '_pages/news/en'
  values:
    layout: news
    language: 'en'
    permalink: 'en/news/:basename'
    type: 'news'
    sitemap: 'true'
-
  scope:
    path: '_pages/news/it'
  values:
    layout: news
    language: 'it'
    permalink: 'it/news/:basename'
    type: 'news'
    sitemap: 'true'
-
  scope:
    path: '_pages/projects/en'
  values:
    layout: project
    language: 'en'
    permalink: 'en/projects/:basename'
    type: 'project'
    sitemap: 'true'
-
  scope:
    path: '_pages/projects/it'
  values:
    layout: project
    language: 'it'
    permalink: 'it/progetti/:basename'
    type: 'project'
    sitemap: 'true'

encoding: "UTF-8"

whitelist: 
  - jekyll-redirect-from
